### ISSUE TITLE
NoSuchMethodError with Dropwizard 1.1.0-rc1

### ISSUE THREAD

**Issue by maksymgendin** [ahus1/keycloak-dropwizard-integration#10]
```
WARN  [2017-03-06 18:01:31,846] org.eclipse.jetty.server.HttpChannel:
! **java.lang.NoSuchMethodError: org.eclipse.jetty.server.Request.getSessionManager()Lorg/eclipse/jetty/server/SessionManager;**
! at org.keycloak.adapters.jetty.core.AbstractKeycloakJettyAuthenticator.validateRequest(AbstractKeycloakJettyAuthenticator.java:293)
! at de.ahus1.keycloak.dropwizard.KeycloakDropwizardAuthenticator.validateRequest(KeycloakDropwizardAuthenticator.java:42)
! at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:483)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
! at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1584)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
! at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240)
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:561)
! at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:68)
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at org.eclipse.jetty.server.Server.handle(Server.java:564)
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
! at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
! at java.lang.Thread.run(Thread.java:745)
```

Is this a problem with the bundled Jetty 9.4.X?

**Comment by ahus1** [comment]
Most probably yes. As of http://www.keycloak.org/downloads.html Keycloak only supports Jetty 9.3

For Jetty 9.3 I've provided a pull request for Keycloak (https://issues.jboss.org/browse/KEYCLOAK-2684). Do you want to give it a try for Jetty 9.4?

**Comment by reneploetz** [comment]
I added https://issues.jboss.org/browse/KEYCLOAK-4537 and will provide the pull request as soon as my local tests are finished (unless somebody is faster of course ;) )

**Comment by maksymgendin** [comment]
@ahus1 @reneploetz Thank you very much for extremely fast reply and solution! Let us wait :hourglass_flowing_sand:

**Comment by maksymgendin** [comment]
@ahus1 @reneploetz Great news, Keycloak 3.0.0.CR1 is released with Jetty 9.4 adapter!

**Comment by maksymgendin** [comment]
@ahus1 @reneploetz I've provided a pull request, guys.

**Comment by ahus1** [comment]
Thanks @reneploetz and @maksymgendin  - the release is now out on maven central!
