### ISSUE TITLE
500 Internal server error when running the keycloak-dropwizard-jaxrs-example example

### ISSUE THREAD

**Issue by horsey** [ahus1/keycloak-dropwizard-integration#24]
Hello @ahus1: 
I get the following exception when trying to run the example program:

````
INFO  [2019-02-26 15:00:09,692] org.eclipse.jetty.server.Server: Started @7948ms
0:0:0:0:0:0:0:1 - - [26/Feb/2019:15:00:30 +0000] "GET / HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36" 10103
WARN  [2019-02-26 15:00:40,769] org.eclipse.jetty.server.HttpChannel: /
! java.security.NoSuchAlgorithmException: ECDSA KeyFactory not available
! at java.security.KeyFactory.<init>(KeyFactory.java:138)
! at java.security.KeyFactory.getInstance(KeyFactory.java:172)
! at org.keycloak.jose.jwk.JWKParser.createECPublicKey(JWKParser.java:111)
! ... 45 common frames omitted
! Causing: java.lang.RuntimeException: java.security.NoSuchAlgorithmException: ECDSA KeyFactory not available
! at org.keycloak.jose.jwk.JWKParser.createECPublicKey(JWKParser.java:114)
! at org.keycloak.jose.jwk.JWKParser.toPublicKey(JWKParser.java:78)
! at org.keycloak.util.JWKSUtils.getKeysForUse(JWKSUtils.java:41)
! at org.keycloak.adapters.rotation.JWKPublicKeyLocator.sendRequest(JWKPublicKeyLocator.java:101)
! at org.keycloak.adapters.rotation.JWKPublicKeyLocator.getPublicKey(JWKPublicKeyLocator.java:63)
! at org.keycloak.adapters.rotation.AdapterTokenVerifier.getPublicKey(AdapterTokenVerifier.java:121)
````

Keycloak version: 4.8.3.Final
Dropwizard version: 1.3.9

**Comment by ahus1** [comment]
There are multiple example programs in this project. Could you please run the tests in the project and point to a test that fails? On my machine all of them work. 

Could you please name the JDK you are using?

**Comment by horsey** [comment]
@ahus1 
Thanks for your reply. The issue was a case of an outdated version of the code I had.  It got sorted once I refreshed the code.
