### ISSUE TITLE
java.lang.IllegalStateException: InjectionManagerFactory not found.

### ISSUE THREAD

**Issue by robshep** [ahus1/keycloak-dropwizard-integration#36]
Running master @fca9af0 the example: 

    mvn test -pl keycloak-dropwizard-jaxrs-example -am -Pkeycloak-dropwizard-jaxrs-example

fails with:

```Caused by: java.lang.IllegalStateException: InjectionManagerFactory not found.
	at org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:74)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:74)
	at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:69)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:347)
	at javax.servlet.GenericServlet.init(GenericServlet.java:180)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:602)
```

_Originally posted by @gjvoosten in https://github.com/ahus1/keycloak-dropwizard-integration/issues/31#issuecomment-630610979_

... and I needed to add a dependency:
```
        <dependency>
            <groupId>org.glassfish.jersey.inject</groupId>
            <artifactId>jersey-hk2</artifactId>
            <version>2.30.1</version>
        </dependency>
```
to be able to run e.g. `mvn test -pl keycloak-dropwizard-jaxrs-example -am -Pkeycloak-dropwizard-jaxrs-example`

**Comment by gjvoosten** [comment]
PR makes:
```
mvn test -pl keycloak-dropwizard-jaxrs-example -am
```
pass; note that:
```
mvn test -pl keycloak-dropwizard-jaxrs-example -am -Pkeycloak-dropwizard-jaxrs-example
```
appears to 'hang' at the end.
